name: flutter_packages
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

  # https://pub.dev/packages/fluttertoast
  fluttertoast: ^8.2.4

  # https://pub.dev/packages/logger
  logger: ^2.1.0

  # https://pub.dev/packages/flutter_riverpod
  flutter_riverpod: ^2.5.1

  # https://pub.dev/packages/device_info_plus
  device_info_plus: ^9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
